apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2020-04-05T21:41:05Z"
  generation: 14
  labels:
    app: worker
  name: worker
  namespace: default
  resourceVersion: "249294"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/worker
  uid: 4f35716c-65bd-49dc-8f05-b159438c2d58
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2020-04-10T21:19:23Z"
    lastUpdateTime: "2020-04-10T21:19:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-05T21:41:05Z"
    lastUpdateTime: "2020-04-10T21:42:57Z"
    message: ReplicaSet "worker-745744775c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 14
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
